library(lubridate)
power<-read.csv('household_power_cons_subset_feb1and2_2007.csv')
png(file = "plot3.png",width = 480, height = 480, units = "px")
date_time<-paste(power$Date,power$Time, sep = " ")
posix_date_time<-dmy_hms(date_time)
max<-max(max(power$Sub_metering_1),max(power$Sub_metering_2),max(power$Sub_metering_3))
plot(posix_date_time,power$Sub_metering_1,ylim=c(0,max),xlab='',ylab='',col="black",type='l',xaxt='n')
par(new=T)
plot(posix_date_time,power$Sub_metering_2,ylim=c(0,max),xlab='',ylab='',col="red",type='l',xaxt='n')
par(new=T)
plot(posix_date_time,power$Sub_metering_3,ylim=c(0,max),xlab='',ylab='Energy sub metering',col="blue",type='l')
legend("topright",lty=c(1,1,1),col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()